// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.

use composite_methods::{COMPOSITE_ELF, COMPOSITE_ID};
use hallow_host::multiply;
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {
    // Some party "Alice" picks two numbers and multiplies them, producing a receipt that attests
    // the fact that Alice knows the factorization of the product. This is similar to RSA keygen.
    let (multiply_receipt, n) = multiply(17, 23);

    // Alice might then send to "Bob" the product and the receipt that proves Alice knows the
    // factorization. Bob then raises a secret number to a public exponent mod the composite number
    // chosen by Alice. This is like an RSA encryption from Bob to Alice, verified by the zkVM.
    let env = ExecutorEnv::builder()
        // add_assumption makes the receipt to be verified available to the prover.
        .add_assumption(multiply_receipt)
        .write(&(n, 9u64, 100u64))
        .unwrap()
        .build()
        .unwrap();

    let receipt = default_prover().prove(env, COMPOSITE_ELF).unwrap().receipt;

    // Anybody who receives the receipt for the exponentiation is assured both that:
    // A) The modulus n included in the journal has a known factorization.
    // B) The number c is the result of exponentiation of some known secret x ^ e mod n.
    //
    // These two statements are proven with a single receipt via composition.
    receipt.verify(COMPOSITE_ID).unwrap();

    // Decode the receipt to get (n, e, and c = x^e mod n).
    let (n, e, c): (u64, u64, u64) = receipt.journal.decode().unwrap();

    println!("{c} is the result of exponentiation by {e} under composite {n} with known factors");
}
