[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.0.5" }
methods = { path = "../methods" }
anyhow = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
