[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0.1" }

[dependencies]
risc0-steel = "0.11.1"

[package.metadata.risc0]
methods = ["guest"]
